apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base


patchesStrategicMerge:
  - base.yaml

namespace: staging

configMapGenerator:
  - name: sendbox-auth
    envs:
      - config
      - shared
  - name: sendbox-oauth
    envs:
      - oauth