apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base


patchesStrategicMerge:
  - base.yaml

namespace: staging

configMapGenerator:
  - name: sendbox-auth
    behavior: merge
    envs:
      - config
  - name: sendbox-oauth
    envs:
      - oauth
  - name: sendbox-shared
    behavior: merge
    envs:
      - shared