apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
#  - github.com/rustyro/config//base?ref=master
#  - git::ssh://git@github:config.git//base?ref=master


#patches:
#  - path: base.yaml
#    target:
#      kind: Deployment
#      labelSelector: org=sendbox

patchesStrategicMerge:
  - base.yaml

configMapGenerator:
  - name: sendbox-auth
    envs:
      - config
      - shared
  - name: sendbox-oauth
    envs:
      - oauth