apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
#  - github.com/rustyro/config//base?ref=master
#  - git::ssh://git@github:config.git//base?ref=master


#patches:
#  - path: base.yaml
#    target:
#      kind: Deployment
#      labelSelector: org=sendbox

patchesStrategicMerge:
  - base.yaml

namespace: production

configMapGenerator:
  - name: sendbox-auth
    behavior: merge
    envs:
      - config
  - name: sendbox-oauth
    envs:
      - oauth
  - name: sendbox-shared
    behavior: merge
    envs:
      - shared