apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - services.yaml
  - base_config  # this dir will be populated with a git clone from an external command

configMapGenerator:
  - name: sendbox-auth
    envs:
      - config.env



