apiVersion: v1
kind: Service
metadata:
  name: sendbox-auth-web
  labels:
    app: sendbox-auth-web
    ver: v0.0.1
    type: web
spec:
  selector:
    app: sendbox-auth
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: sendbox-auth-grpc
  labels:
    app: sendbox-auth-grpc
    ver: v0.0.1
    type: grpc
spec:
  selector:
    app: sendbox-auth
  ports:
    - port: 50051
      targetPort: 50051
      protocol: TCP


---

apiVersion: v1
kind: Service
metadata:
  name: sendbox-oauth-web
  labels:
    app: sendbox-oauth-web
    ver: v0.0.1
    type: web
spec:
  selector:
    app: sendbox-auth
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
